name: test golang files
on: 
  workflow_dispatch: 
jobs:
  test_golang:
    runs-on: ubuntu-latest
    steps:

      - name: Job start
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Install GoLang v1.24.9
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.9"

      - name: Display Go version
        run: go version